# Vocab vs Fixed-Topic Cosine Similarity

This notebook loads the OPT-2.7b embedding matrix and vocabulary from
`data/complete/`, then computes the **cosine similarity** between **every
vocab token** and a small set of **fixed topic words** you provide.

**Steps before running:**
1. Upload the `data/complete/` folder (`opt27_embeddings.npy` + `opt27_vocab.csv`)
   to your Google Drive.
2. Edit `DATA_DIR` below so it points at that folder.
3. Edit the `TOPICS` list in the "Fixed Topics" cell with your own words.

In [2]:
import os
from collections import defaultdict

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount("/content/drive",force_remount=True)

Mounted at /content/drive

In [3]:

DATA_DIR = "/content/drive/MyDrive/minor_project/"

embeddings = np.load(os.path.join(DATA_DIR, "opt27_embeddings.npy")).astype(np.float32)
vocab_df   = pd.read_csv(os.path.join(DATA_DIR, "opt27_vocab.csv"))

print("embeddings:", embeddings.shape, embeddings.dtype)
print("vocab rows:", len(vocab_df))


vocab_df = vocab_df[vocab_df["token_id"].isin(range(embeddings.shape[0]))]
vocab_df = vocab_df.dropna(subset=["token"])
token_ids = vocab_df["token_id"].to_numpy()
tokens    = vocab_df["token"].to_numpy()
emb       = embeddings[token_ids]

print("aligned vocab x embedding:", emb.shape)

embeddings: (50272, 2560) float32
vocab rows: 50265
aligned vocab x embedding: (50260, 2560)

In [4]:

id_to_token = dict(zip(token_ids, tokens))
token_to_id = {tok: tid for tid, tok in id_to_token.items()}

id_to_index = {tid: i for i, tid in enumerate(token_ids)}

# OPT BPE prepends a "Ġ" space-marker to most word tokens.
# Map a cleaned (lowercased, no "Ġ") form to every matching token_id.
clean_to_ids = defaultdict(list)
for tid, tok in id_to_token.items():
    clean_to_ids[tok.replace("Ġ", "").lower()].append(tid)

def resolve_topic(word):
    """Return token_id(s) for a topic word.

    Tries the plain word, then the 'Ġ'-prefixed BPE form, then falls back
    to a cleaned-text lookup (handles casing and the 'Ġ' marker).
    """
    for cand in (word, "Ġ" + word):
        if cand in token_to_id:
            return [token_to_id[cand]]
    return clean_to_ids.get(word.lower(), [])

# Unit-normalize each embedding row once (rows already aligned)
norm_emb = emb / np.linalg.norm(emb, axis=1, keepdims=True)

## Fixed Topics

Edit the `TOPICS` list below with your own topic words. Every topic should
be a word/phrase that exists in the model vocab (e.g. `"technology"` maps to
the token `Ġtechnology`). The next cell reports which token each topic
resolved to, so you can verify.

In [5]:
TOPICS = [
    "technology",
    "medicine",
    "sports",
    "politics",
    "science",
    "entertainment",
    "finance",
    "history"
]

In [6]:
# ------------------------------------------------------------------
# Resolve each topic to its vocab token_id(s)
# ------------------------------------------------------------------
topic_ids = []
for word in TOPICS:
    ids = resolve_topic(word)
    resolved = [id_to_token[i] for i in ids]
    print(f"{word!r:20} -> {resolved}")
    topic_ids.append(ids)

'technology'         -> ['technology']
'medicine'           -> ['Ġmedicine']
'sports'             -> ['sports']
'politics'           -> ['politics']
'science'            -> ['science']
'entertainment'      -> ['Ġentertainment']
'finance'            -> ['Ġfinance']
'history'            -> ['history']

In [7]:
# ------------------------------------------------------------------
# Cosine similarity matrix, shape (num_vocab, num_topics):
#   sim[i, j] = cosine(embedding(vocab_token_i), embedding(topic_j))
#
# Each topic is represented by the mean of its resolved token embeddings
# (re-normalized to unit length).
# ------------------------------------------------------------------
sim = np.zeros((len(token_ids), len(TOPICS)), dtype=np.float32)

for j, ids in enumerate(topic_ids):
    if not ids:
        print(f"WARNING: topic {TOPICS[j]!r} not found in vocab, skipping")
        continue
    rows = [id_to_index[i] for i in ids]
    topic_vec = norm_emb[rows].mean(axis=0)
    topic_vec = topic_vec / np.linalg.norm(topic_vec)
    sim[:, j] = norm_emb @ topic_vec

print("similarity matrix:", sim.shape)

similarity matrix: (50260, 8)

In [8]:
# ------------------------------------------------------------------
# Top-N most similar vocab tokens for each topic
# ------------------------------------------------------------------
TOP_N = 25

for j, word in enumerate(TOPICS):
    order = np.argsort(-sim[:, j])
    top = pd.DataFrame({
        "token":      tokens[order[:TOP_N]],
        "similarity": sim[order[:TOP_N], j].round(4),
    }).reset_index(drop=True)
    print(f"\n=== Most similar to '{word}' ===")
    display(top)

=== Most similar to 'technology' ===

               token  similarity
0         technology      1.0000
1         Technology      0.7134
2        ĠTechnology      0.6306
3        Ġtechnology      0.6282
4      Ġtechnologies      0.5620
5     Ġtechnological      0.5091
6              ĠTECH      0.5017
7   Ġtechnologically      0.4609
8               tech      0.4376
9        otechnology      0.4127
10             Ġtech      0.4063
11             techn      0.3922
12              Tech      0.3909
13     ĠTechnologies      0.3786
14         technical      0.3751
15           devices      0.3544
16             ĠTech      0.3534
17           science      0.3506
18          chnology      0.3485
19          software      0.3466
20           Ġtechno      0.3422
21       engineering      0.3407
22            Ġtechn      0.3327
23        ĠTechnique      0.3289
24       ĠTechniques      0.3185

=== Most similar to 'medicine' ===

              token  similarity
0         Ġmedicine      1.0000
1         ĠMedicine      0.6859
2        Ġmedicines      0.5869
3       Ġmedication      0.4981
4             Medic      0.3821
5      Ġmedications      0.3794
6          Ġmedical      0.3786
7        Ġmedicinal      0.3659
8            Ġmedic      0.3222
9              Ġmed      0.3171
10          medical      0.3101
11          Medical      0.2992
12           ĠMedic      0.2908
13         Ġdoctors      0.2886
14      Ġhealthcare      0.2770
15  Ġpharmaceutical      0.2722
16       Ġphysician      0.2707
17      Ġphysicians      0.2687
18              med      0.2680
19         ĠMedical      0.2673
20          Ġdoctor      0.2603
21             ĠMED      0.2597
22      Ġpsychiatry      0.2569
23         Ġtherapy      0.2565
24         Ġsurgery      0.2450

=== Most similar to 'sports' ===

           token  similarity
0         sports      1.0000
1         Sports      0.6215
2        Ġsports      0.5811
3        ĠSPORTS      0.5359
4        ĠSports      0.5314
5          Sport      0.4299
6      Ġsporting      0.3919
7     Ġathletics      0.3774
8         Ġsport      0.3736
9         ĠSport      0.3725
10    basketball      0.3530
11     Ġathletes      0.3455
12          ESPN      0.3311
13     Ġathletic      0.3206
14       ĠAthlet      0.3181
15      football      0.3180
16      Ġathlete      0.3179
17         ports      0.3155
18      ĠEsports      0.3065
19       Ġathlet      0.3061
20      Ġesports      0.3008
21     ĠSporting      0.2993
22      Football      0.2934
23  Ġathleticism      0.2834
24      ĠeSports      0.2830

=== Most similar to 'politics' ===

           token  similarity
0       politics      1.0000
1      Ġpolitics      0.6286
2       Politics      0.6125
3      ĠPolitics      0.6073
4         ĠPOLIT      0.5134
5      political      0.5051
6          polit      0.4339
7      Political      0.4330
8          Polit      0.3975
9        olitics      0.3934
10      Ġpolitic      0.3807
11   Ġpolitician      0.3653
12    ĠPolitical      0.3587
13        Ġpolit      0.3564
14  Ġpoliticians      0.3554
15         Ġgeop      0.3486
16      olitical      0.3391
17        ĠPolit      0.3149
18      partisan      0.3067
19     ĠPolitico      0.3036
20  Ġpolitically      0.3029
21     democracy      0.2953
22           POL      0.2893
23       history      0.2858
24    Ġpolitical      0.2851

=== Most similar to 'science' ===

              token  similarity
0           science      1.0000
1           Science      0.6816
2          Ġscience      0.6601
3          ĠScience      0.6017
4        scientific      0.5548
5            scient      0.5355
6         Ġsciences      0.4980
7               sci      0.4766
8        Scientists      0.4711
9       ĠScientists      0.4587
10       Ġscientist      0.4499
11      Ġscientists      0.4464
12      Ġscientific      0.4343
13  Ġscientifically      0.4334
14           Scient      0.4186
15           cience      0.4166
16       ĠScientist      0.4039
17        ĠSciences      0.3943
18          biology      0.3565
19             Ġsci      0.3510
20       technology      0.3506
21            IENCE      0.3482
22       Ġastronomy      0.3482
23          Ġscient      0.3439
24      ĠScientific      0.3367

=== Most similar to 'entertainment' ===

             token  similarity
0   Ġentertainment      1.0000
1   ĠEntertainment      0.5993
2       Ġentertain      0.5287
3    Ġentertaining      0.4505
4       Ġamusement      0.4135
5     Ġentertained      0.4110
6          Ġentert      0.3578
7           Ġmusic      0.3102
8         tainment      0.3023
9       Ġenjoyment      0.3000
10          ĠENTER      0.2982
11         Ġcomedy      0.2802
12         Ġgaming      0.2697
13          Ġamuse      0.2629
14     Ġrecreation      0.2503
15      Ġenjoyable      0.2386
16           Enter      0.2332
17          ertain      0.2325
18        Ġleisure      0.2306
19    Ġhospitality      0.2247
20         Ġcinema      0.2229
21          Ġmovie      0.2203
22   Ġrecreational      0.2182
23     Ġtelevision      0.2174
24    Ġeducational      0.2138

=== Most similar to 'finance' ===

           token  similarity
0       Ġfinance      1.0000
1       ĠFinance      0.7320
2     Ġfinancing      0.4813
3      Ġfinances      0.4648
4     Ġfinancial      0.4316
5         Ġfinan      0.4184
6         inance      0.3970
7      Ġfinanced      0.3689
8      financial      0.3491
9      Financial      0.3231
10  Ġfinancially      0.3216
11    ĠFinancial      0.3104
12         Ġfund      0.3026
13      Ġfunding      0.2761
14          ĠFin      0.2667
15      Ġbanking      0.2604
16          ĠFIN      0.2541
17    Ġeconomics      0.2515
18       Ġfiscal      0.2479
19        Ġfunds      0.2474
20    Ġtreasurer      0.2440
21           Fin      0.2427
22     Ġpayments      0.2285
23           fin      0.2282
24      Ġbankers      0.2253

=== Most similar to 'history' ===

            token  similarity
0         history      1.0000
1         History      0.7101
2        ĠHistory      0.6912
3        Ġhistory      0.6735
4      Ġhistories      0.6128
5          ISTORY      0.5373
6     Ġhistorians      0.4829
7            hist      0.4516
8         Ġhistor      0.4485
9      Ġhistorian      0.4348
10       historic      0.4312
11           Hist      0.4136
12          ĠHist      0.3826
13    Ġhistorical      0.3618
14    ĠHistorical      0.3509
15  ĠHistorically      0.3391
16          Ġhist      0.2983
17     Ġantiquity      0.2924
18     Ġbackstory      0.2873
19       tymology      0.2869
20       politics      0.2858
21      Ġfolklore      0.2808
22          facts      0.2761
23      ĠHistoric      0.2745
24     Ġmythology      0.2739

In [9]:

topicality = pd.DataFrame({
    "token":          tokens,
    "topic":          [TOPICS[j] for j in sim.argmax(axis=1)],
    "max_similarity": sim.max(axis=1).round(4),
}).sort_values("max_similarity", ascending=False).reset_index(drop=True)

display(topicality.head(50))


out = pd.DataFrame({"token_id": token_ids, "token": tokens})
for j, word in enumerate(TOPICS):
    out[f"sim_{word}"] = sim[:, j].round(4)
out.to_csv(os.path.join(DATA_DIR, "topic_cosine_similarity.csv"), index=False)
print("\nsaved topic_cosine_similarity.csv")

               token          topic  max_similarity
0           Ġfinance        finance          1.0000
1     Ġentertainment  entertainment          1.0000
2          Ġmedicine       medicine          1.0000
3            science        science          1.0000
4         technology     technology          1.0000
5             sports         sports          1.0000
6            history        history          1.0000
7           politics       politics          1.0000
8           ĠFinance        finance          0.7320
9         Technology     technology          0.7134
10           History        history          0.7101
11          ĠHistory        history          0.6912
12         ĠMedicine       medicine          0.6859
13           Science        science          0.6816
14          Ġhistory        history          0.6735
15          Ġscience        science          0.6601
16       ĠTechnology     technology          0.6306
17         Ġpolitics       politics          0.6286
18       Ġtechnology     technology          0.6282
19            Sports         sports          0.6215
20        Ġhistories        history          0.6128
21          Politics       politics          0.6125
22         ĠPolitics       politics          0.6073
23          ĠScience        science          0.6017
24    ĠEntertainment  entertainment          0.5993
25        Ġmedicines       medicine          0.5869
26           Ġsports         sports          0.5811
27     Ġtechnologies     technology          0.5620
28        scientific        science          0.5548
29            ISTORY        history          0.5373
30           ĠSPORTS         sports          0.5359
31            scient        science          0.5355
32           ĠSports         sports          0.5314
33        Ġentertain  entertainment          0.5287
34            ĠPOLIT       politics          0.5134
35    Ġtechnological     technology          0.5091
36         political       politics          0.5051
37             ĠTECH     technology          0.5017
38       Ġmedication       medicine          0.4981
39         Ġsciences        science          0.4980
40       Ġhistorians        history          0.4829
41        Ġfinancing        finance          0.4813
42               sci        science          0.4766
43        Scientists        science          0.4711
44         Ġfinances        finance          0.4648
45  Ġtechnologically     technology          0.4609
46       ĠScientists        science          0.4587
47              hist        history          0.4516
48     Ġentertaining  entertainment          0.4505
49        Ġscientist        science          0.4499

saved topic_cosine_similarity.csv